syntax = "proto3";

option ruby_package = "Tucana::Sagittarius::Rails";

package sagittarius_rails;

import "shared.errors.proto";
import "shared.runtime_status.proto";

message RuntimeStatusUpdateRequest {
  oneof status {
    shared.ModuleStatus module_status = 1;
    shared.RuntimeStatus runtime_status = 2;
  }
}

message RuntimeStatusUpdateResponse {
  bool success = 1;
  optional shared.ServiceError error = 2;
}

service RuntimeStatusService {
  rpc Update(RuntimeStatusUpdateRequest) returns (RuntimeStatusUpdateResponse) {}
}
